blank_issues_enabled: false
contact_links:
  - name: 🚀 Discussions and Proposals
    url: https://github.com/commutatus/cm-airtel-hackathon/discussions
    about: Visit our GitHub Discussions page to suggest an idea to make it better.
