name: 💡 Feature request
description: Request a feature that helps you built the platform better.
title: ''
labels: ['enhancement']
assignees:
  - AdityaTiwari2102

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of what the feature is.
    validations:
      required: true

  - type: textarea
    id: workarounds
    attributes:
      label: Current workarounds
      description: Is there a way to achieve this behavior at the moment through some hack?

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Have you seen this behavior somewhere else where we can test it?

  - type: textarea
    id: extra
    attributes:
      label: Code example, screenshot, or link to a repository
      description: |
        Please provide a link to a repository on GitHub, or provide a minimal code example to help explain your problem.
        You may provide a screenshot or recording of the application to give an idea about the changes on UI.
        Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve
